name: 'boilerplate-adonis'
version: '3.1'
services:
  database:
    container_name: boilerplate-adonis-database
    image: postgres
    environment:
      TZ: Asia/Jakarta
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerplate
    ports:
      - 5432:5432
  app:
    container_name: boilerplate-adonis-app
    depends_on:
      - database
    build: .
    env_file:
      - .env
    ports:
      - 3333:3333
    command: node ace serve --watch
    links:
      - database
    volumes:
      - ./app:/backend/app
      - ./commands:/backend/commands
      - ./config:/backend/config
      - ./contracts:/backend/contracts
      - ./database:/backend/database
      - ./providers:/backend/providers
      - ./resources:/backend/resources
      - ./start:/backend/start
      - ./tests:/backend/tests
      - ./tmp:/backend/tmp