name: 'boilerplate-production'
version: '3.1'
services:
  database:
    image: postgres
    environment:
      TZ: Asia/Jakarta
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerplate
    ports:
      - 5432:5432
  app:
    depends_on:
      - database
    build: .
    env_file:
      - .env
    ports:
      - 3333:3333
    entrypoint: node ace migration:fresh --seed