name: 'boilerplate-backend'
version: '3.1'
services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerplate_node
    ports:
      - 5432:5432
  app:
    container_name: app
    depends_on:
      - database
    build: .
    command: node ace serve --watch
    env_file:
      - .env
    environment:
      PG_HOST: host.docker.internal
      PG_USER: root
      PG_PASSWORD: root
      PG_DB_NAME: boilerplate_node
    ports:
      - 3333:3333